import "server-only";

import { randomUUID } from "node:crypto";
import path from "node:path";

import { get, put } from "@vercel/blob";

const EXTENSION_CONTENT_TYPES: Record<string, string> = {
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".png": "image/png",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".heic": "image/heic",
  ".pdf": "application/pdf",
  ".doc": "application/msword",
  ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
};

const DEFAULT_CONTENT_TYPE = "application/octet-stream";

function extensionFromUrl(url: string): string {
  try {
    const ext = path.extname(new URL(url).pathname).toLowerCase();
    return ext in EXTENSION_CONTENT_TYPES ? ext : "";
  } catch {
    return "";
  }
}

export function contentTypeForStorageKey(storageKey: string): string {
  return EXTENSION_CONTENT_TYPES[path.extname(storageKey).toLowerCase()] ?? DEFAULT_CONTENT_TYPE;
}

/** A storage key is always exactly `{uuid}{ext}`, generated by
 *  `downloadAndStoreDocument` — never derived from user input on the
 *  write side. Validated again here since the read side (the serving
 *  route) takes it from a URL param, which is attacker-controllable;
 *  this pattern makes path traversal structurally impossible (no `/`
 *  or `..` can match), not just filtered. Doubles as the Blob store
 *  pathname. */
const STORAGE_KEY_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}(\.[a-z0-9]{1,5})?$/i;

export function isInternalStorageKey(key: string): boolean {
  return STORAGE_KEY_PATTERN.test(key);
}

/**
 * Fetches a document link (typically a short-lived signed URL from the
 * source application portal — some expire within an hour) and persists
 * the bytes to a private Vercel Blob store, so the document survives
 * long after the original link expires. Meant to be called at import
 * time, while the link is presumably still fresh. Returns `null` on any
 * failure (network error, non-2xx, expired token, empty body) — the
 * caller falls back to keeping the original external link rather than
 * failing the whole row over one bad document.
 *
 * Private access (not public) is deliberate: these are applicants' government
 * ID, NYSC, and degree documents — a real production requirement, not a
 * preference. Reading a private blob requires BLOB_READ_WRITE_TOKEN,
 * which only ever runs server-side (see readStoredDocument), never
 * reaching the client.
 */
export async function downloadAndStoreDocument(url: string): Promise<{ storageKey: string } | null> {
  try {
    const response = await fetch(url, { signal: AbortSignal.timeout(15_000) });
    if (!response.ok) return null;
    const buffer = Buffer.from(await response.arrayBuffer());
    if (buffer.length === 0) return null;

    const storageKey = `${randomUUID()}${extensionFromUrl(url)}`;
    await put(storageKey, buffer, { access: "private", contentType: contentTypeForStorageKey(storageKey) });
    return { storageKey };
  } catch {
    return null;
  }
}

export async function readStoredDocument(storageKey: string): Promise<Buffer | null> {
  if (!isInternalStorageKey(storageKey)) return null;
  try {
    const result = await get(storageKey, { access: "private" });
    if (!result) return null;
    return Buffer.from(await new Response(result.stream).arrayBuffer());
  } catch {
    return null;
  }
}
