/**
 * Canonical audit action strings (amendment 10) — every module writes
 * from this list rather than inventing its own strings, so the Audit
 * Trail viewer has one consistent vocabulary from the start.
 */
export const AUDIT_ACTIONS = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
  USER_LOGOUT: "USER_LOGOUT",
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_ACTIVATED: "USER_ACTIVATED",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  USER_STATUS_CHANGED: "USER_STATUS_CHANGED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  USER_PASSWORD_RESET: "USER_PASSWORD_RESET",
  USER_PASSWORD_CHANGED: "USER_PASSWORD_CHANGED",

  APPLICANTS_IMPORTED: "APPLICANTS_IMPORTED",
  APPLICANTS_EXPORTED: "APPLICANTS_EXPORTED",
  APPLICANT_RECORD_EDITED: "APPLICANT_RECORD_EDITED",
  APPLICANT_DELETED: "APPLICANT_DELETED",

  ELIGIBILITY_CRITERION_CREATED: "ELIGIBILITY_CRITERION_CREATED",
  ELIGIBILITY_CRITERION_UPDATED: "ELIGIBILITY_CRITERION_UPDATED",
  ELIGIBILITY_DECISION_RECORDED: "ELIGIBILITY_DECISION_RECORDED",

  REVIEW_ASSIGNED: "REVIEW_ASSIGNED",
  REVIEW_SUBMITTED: "REVIEW_SUBMITTED",
  REVIEW_THIRD_REVIEWER_ASSIGNED: "REVIEW_THIRD_REVIEWER_ASSIGNED",

  // Review assignment engine (Phase 3B §14)
  ASSIGNMENT_ACCEPTED: "ASSIGNMENT_ACCEPTED",
  ASSIGNMENT_REASSIGNED: "ASSIGNMENT_REASSIGNED",
  ASSIGNMENT_CANCELLED: "ASSIGNMENT_CANCELLED",
  CONFLICT_OF_INTEREST_DECLARED: "CONFLICT_OF_INTEREST_DECLARED",
  REVIEW_ESCALATION_TRIGGERED: "REVIEW_ESCALATION_TRIGGERED",
  REVIEWER_CAPACITY_CHANGED: "REVIEWER_CAPACITY_CHANGED",

  // Programme Secretariat review operations workspace (Phase 3D)
  ADMINISTRATIVE_NOTE_CREATED: "ADMINISTRATIVE_NOTE_CREATED",
  REVIEW_OPERATIONS_EXPORTED: "REVIEW_OPERATIONS_EXPORTED",

  // Review framework & scoring engine (Phase 3A §17)
  REVIEW_STAGE_CREATED: "REVIEW_STAGE_CREATED",
  REVIEW_STAGE_UPDATED: "REVIEW_STAGE_UPDATED",
  REVIEW_FRAMEWORK_CREATED: "REVIEW_FRAMEWORK_CREATED",
  REVIEW_FRAMEWORK_UPDATED: "REVIEW_FRAMEWORK_UPDATED",
  REVIEW_FRAMEWORK_PUBLISHED: "REVIEW_FRAMEWORK_PUBLISHED",
  REVIEW_FRAMEWORK_RETIRED: "REVIEW_FRAMEWORK_RETIRED",
  REVIEW_CRITERION_CREATED: "REVIEW_CRITERION_CREATED",
  REVIEW_CRITERION_UPDATED: "REVIEW_CRITERION_UPDATED",
  REVIEW_CRITERION_RETIRED: "REVIEW_CRITERION_RETIRED",
  REVIEW_CREATED: "REVIEW_CREATED",
  REVIEW_DRAFT_SCORE_SAVED: "REVIEW_DRAFT_SCORE_SAVED",
  REVIEW_REOPENED: "REVIEW_REOPENED",
  REVIEW_RECALCULATED: "REVIEW_RECALCULATED",
  REVIEW_SCORE_CHANGED_AFTER_REOPEN: "REVIEW_SCORE_CHANGED_AFTER_REOPEN",
  REVIEW_ADMINISTRATIVE_OVERRIDE: "REVIEW_ADMINISTRATIVE_OVERRIDE",

  INTERVIEW_SCHEDULED: "INTERVIEW_SCHEDULED",
  INTERVIEW_SCORE_SUBMITTED: "INTERVIEW_SCORE_SUBMITTED",

  COMMITTEE_VOTE_CAST: "COMMITTEE_VOTE_CAST",
  COMMITTEE_DECISION_RECORDED: "COMMITTEE_DECISION_RECORDED",

  EXECUTIVE_APPROVAL_DECIDED: "EXECUTIVE_APPROVAL_DECIDED",

  ADMISSION_OFFER_ISSUED: "ADMISSION_OFFER_ISSUED",
  ADMISSION_OFFER_STATUS_CHANGED: "ADMISSION_OFFER_STATUS_CHANGED",

  APPLICATION_STAGE_CHANGED: "APPLICATION_STAGE_CHANGED",
  PERMISSION_CHANGED: "PERMISSION_CHANGED",

  // Enterprise Configuration Centre (Release 1.5)
  CONFIGURATION_UPDATED: "CONFIGURATION_UPDATED",
  PROGRAMME_UPDATED: "PROGRAMME_UPDATED",
  PROGRAMME_WINDOW_UPDATED: "PROGRAMME_WINDOW_UPDATED",
  FEATURE_FLAG_CHANGED: "FEATURE_FLAG_CHANGED",

  // Eligibility QA governance (Release 1.5)
  ELIGIBILITY_RECOMMENDATION_CREATED: "ELIGIBILITY_RECOMMENDATION_CREATED",
  ELIGIBILITY_OVERRIDE_EXECUTED: "ELIGIBILITY_OVERRIDE_EXECUTED",
  ELIGIBILITY_RECOMMENDATION_DISMISSED: "ELIGIBILITY_RECOMMENDATION_DISMISSED",

  // Interview Assignment Engine (Release 1 Module 1) — INTERVIEW_SCHEDULED
  // already existed (declared with the original schema, never used until
  // now); reused as-is rather than duplicated.
  INTERVIEW_SHORTLIST_GENERATED: "INTERVIEW_SHORTLIST_GENERATED",
  INTERVIEW_PANEL_ASSIGNED: "INTERVIEW_PANEL_ASSIGNED",
  INTERVIEW_PANELIST_REASSIGNED: "INTERVIEW_PANELIST_REASSIGNED",
  INTERVIEW_PANELIST_CANCELLED: "INTERVIEW_PANELIST_CANCELLED",
  INTERVIEW_CONFLICT_DECLARED: "INTERVIEW_CONFLICT_DECLARED",
  INTERVIEWER_CAPACITY_CHANGED: "INTERVIEWER_CAPACITY_CHANGED",

  // Interview Workspace (Release 1 Module 2) — INTERVIEW_SCORE_SUBMITTED
  // already existed (declared with the original schema, never used until
  // now); reused as-is.
  INTERVIEW_DRAFT_SCORE_SAVED: "INTERVIEW_DRAFT_SCORE_SAVED",

  // Interview Scheduling (Enterprise Functional Specification Addendum)
  INTERVIEW_AVAILABILITY_SUBMITTED: "INTERVIEW_AVAILABILITY_SUBMITTED",
  INTERVIEW_AVAILABILITY_UPDATED: "INTERVIEW_AVAILABILITY_UPDATED",
  INTERVIEW_SLOTS_GENERATED: "INTERVIEW_SLOTS_GENERATED",
  INTERVIEW_SLOTS_PUBLISHED: "INTERVIEW_SLOTS_PUBLISHED",
  INTERVIEW_SLOT_BOOKED: "INTERVIEW_SLOT_BOOKED",
  INTERVIEW_BOOKING_CONFIRMED: "INTERVIEW_BOOKING_CONFIRMED",
  INTERVIEW_BOOKING_DECLINED: "INTERVIEW_BOOKING_DECLINED",
  INTERVIEW_RESELECTION_REQUESTED: "INTERVIEW_RESELECTION_REQUESTED",
  INTERVIEW_TEAMS_LINK_ADDED: "INTERVIEW_TEAMS_LINK_ADDED",
  INTERVIEW_INVITATIONS_SENT: "INTERVIEW_INVITATIONS_SENT",
  INTERVIEW_REMINDER_SENT: "INTERVIEW_REMINDER_SENT",

  // Interview Scoring Revision (Addendum Module 2, §2.6)
  INTERVIEW_SCORING_CLOSED_WITH_OVERRIDE: "INTERVIEW_SCORING_CLOSED_WITH_OVERRIDE",

  // PAM-P source-document correlation fixes
  INTERVIEW_MODE_SET: "INTERVIEW_MODE_SET",

  // Interview Questions (Addendum Module 3, §3)
  INTERVIEW_QUESTION_CREATED: "INTERVIEW_QUESTION_CREATED",
  INTERVIEW_QUESTION_UPDATED: "INTERVIEW_QUESTION_UPDATED",
  INTERVIEW_SESSION_STARTED: "INTERVIEW_SESSION_STARTED",
  INTERVIEW_SESSION_ENDED: "INTERVIEW_SESSION_ENDED",
  INTERVIEW_ADDITIONAL_QUESTION_SELECTED: "INTERVIEW_ADDITIONAL_QUESTION_SELECTED",

  // Interview Module Completion (Planning Phase 2)
  INTERVIEW_ATTENDANCE_RECORDED: "INTERVIEW_ATTENDANCE_RECORDED",

  // Final Ranking (Addendum Modules 4-5, §9)
  RANKING_COMPOSITE_SCORE_CALCULATED: "RANKING_COMPOSITE_SCORE_CALCULATED",
  RANKING_GENERATED: "RANKING_GENERATED",
  RANKING_TIE_DETECTED: "RANKING_TIE_DETECTED",
  RANKING_TIE_RESOLVED: "RANKING_TIE_RESOLVED",
  RANKING_APPROVED: "RANKING_APPROVED",
  RANKING_REOPENED: "RANKING_REOPENED",
  RANKING_EXPORTED: "RANKING_EXPORTED",

  // Executive Approval Data Model (Planning Phase 3)
  RANKING_APPROVAL_STAGE_RECORDED: "RANKING_APPROVAL_STAGE_RECORDED",

  // Analytics Aggregation + Dashboard + Reporting (Planning Phase 5)
  REPORTS_EXPORTED: "REPORTS_EXPORTED",

  // Eligibility Screening (PAM-P 2026 Eligibility Screening Checklist, §14)
  ELIGIBILITY_SCREENING_CREATED: "ELIGIBILITY_SCREENING_CREATED",
  ELIGIBILITY_SCREENER_ASSIGNED: "ELIGIBILITY_SCREENER_ASSIGNED",
  ELIGIBILITY_SCREENER_REASSIGNED: "ELIGIBILITY_SCREENER_REASSIGNED",
  ELIGIBILITY_CHECKLIST_ITEM_UPDATED: "ELIGIBILITY_CHECKLIST_ITEM_UPDATED",
  ELIGIBILITY_AUTOMATIC_CHECK_PERFORMED: "ELIGIBILITY_AUTOMATIC_CHECK_PERFORMED",
  ELIGIBILITY_CLARIFICATION_REQUESTED: "ELIGIBILITY_CLARIFICATION_REQUESTED",
  ELIGIBILITY_CLARIFICATION_RESOLVED: "ELIGIBILITY_CLARIFICATION_RESOLVED",
  ELIGIBILITY_INTEGRITY_FLAGGED: "ELIGIBILITY_INTEGRITY_FLAGGED",
  ELIGIBILITY_DUPLICATE_DETECTED: "ELIGIBILITY_DUPLICATE_DETECTED",
  ELIGIBILITY_DUPLICATE_RESOLVED: "ELIGIBILITY_DUPLICATE_RESOLVED",
  ELIGIBILITY_MARKED_ELIGIBLE: "ELIGIBILITY_MARKED_ELIGIBLE",
  ELIGIBILITY_MARKED_CLARIFICATION_REQUIRED: "ELIGIBILITY_MARKED_CLARIFICATION_REQUIRED",
  ELIGIBILITY_MARKED_INELIGIBLE: "ELIGIBILITY_MARKED_INELIGIBLE",
  ELIGIBILITY_ESCALATED: "ELIGIBILITY_ESCALATED",
  ELIGIBILITY_MARKED_DISQUALIFIED: "ELIGIBILITY_MARKED_DISQUALIFIED",
  ELIGIBILITY_SECOND_REVIEW_REQUESTED: "ELIGIBILITY_SECOND_REVIEW_REQUESTED",
  ELIGIBILITY_SECOND_REVIEW_COMPLETED: "ELIGIBILITY_SECOND_REVIEW_COMPLETED",
  ELIGIBILITY_SCREENING_REOPENED: "ELIGIBILITY_SCREENING_REOPENED",
  ELIGIBILITY_REMEDIATED: "ELIGIBILITY_REMEDIATED",
  ELIGIBILITY_PROGRESSED_TO_REVIEW: "ELIGIBILITY_PROGRESSED_TO_REVIEW",
  ELIGIBILITY_SCREENING_EXPORTED: "ELIGIBILITY_SCREENING_EXPORTED",
  ELIGIBILITY_CLARIFICATION_DEADLINE_EXTENDED: "ELIGIBILITY_CLARIFICATION_DEADLINE_EXTENDED",
  ELIGIBILITY_CLARIFICATION_DEADLINE_MISSED: "ELIGIBILITY_CLARIFICATION_DEADLINE_MISSED",

  // Microsoft Teams Interview Integration
  INTERVIEW_TEAMS_MEETING_CREATED: "INTERVIEW_TEAMS_MEETING_CREATED",
  INTERVIEW_TEAMS_MEETING_UPDATED: "INTERVIEW_TEAMS_MEETING_UPDATED",
  INTERVIEW_TEAMS_MEETING_CANCELLED: "INTERVIEW_TEAMS_MEETING_CANCELLED",
  INTERVIEW_TEAMS_SYNC_FAILED: "INTERVIEW_TEAMS_SYNC_FAILED",
  INTERVIEW_TEAMS_SYNC_RETRIED: "INTERVIEW_TEAMS_SYNC_RETRIED",
  INTERVIEW_RESCHEDULED: "INTERVIEW_RESCHEDULED",
  INTERVIEW_CANCELLED: "INTERVIEW_CANCELLED",

  // Notification Infrastructure
  NOTIFICATION_ENQUEUED: "NOTIFICATION_ENQUEUED",
  NOTIFICATION_SENT: "NOTIFICATION_SENT",
  NOTIFICATION_FAILED: "NOTIFICATION_FAILED",
  NOTIFICATION_RETRIED: "NOTIFICATION_RETRIED",
  NOTIFICATION_RESENT: "NOTIFICATION_RESENT",
  NOTIFICATION_CANCELLED: "NOTIFICATION_CANCELLED",
  NOTIFICATION_TEMPLATE_UPDATED: "NOTIFICATION_TEMPLATE_UPDATED",
  NOTIFICATION_TEST_SENT: "NOTIFICATION_TEST_SENT",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
