import type { Metadata } from "next";
import Link from "next/link";

import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { getActiveCohort } from "@/lib/cohort";
import { PERMISSIONS } from "@/lib/permissions/catalog";
import { requirePagePermission } from "@/lib/permissions/guard";
import { permissionsForRole } from "@/lib/permissions/rolePermissions";
import { getRankingWorkspace } from "@/modules/ranking/services/rankingWorkspaceService";

import { RankingFilterBar } from "./filter-bar";
import { RankingActions } from "./ranking-actions";
import { TieResolutionCard } from "./tie-resolution-card";
import { DECISION_BAND_LABELS, INELIGIBILITY_LABELS, toRankingWorkspaceViewModel } from "./types";

export const metadata: Metadata = {
  title: "Final Ranking — PAM-P FMS",
};

const DECISION_BAND_BADGE_VARIANT: Record<string, "default" | "secondary" | "outline" | "destructive"> = {
  STRONGLY_RECOMMENDED: "default",
  RECOMMENDED: "secondary",
  RESERVE_BORDERLINE: "outline",
  NOT_RECOMMENDED: "destructive",
};

export default async function RankingPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | undefined>>;
}) {
  const currentUser = await requirePagePermission(PERMISSIONS.RANKING_VIEW);
  const params = await searchParams;
  const cohort = await getActiveCohort();

  const workspace = await getRankingWorkspace(currentUser.id, cohort.id);
  const view = toRankingWorkspaceViewModel(workspace);

  const granted = permissionsForRole(currentUser.role);
  const canGenerate = granted.includes(PERMISSIONS.RANKING_GENERATE);
  const canApprove = granted.includes(PERMISSIONS.RANKING_APPROVE);
  const canReopen = granted.includes(PERMISSIONS.RANKING_REOPEN);
  const canExport = granted.includes(PERMISSIONS.RANKING_EXPORT);
  const canResolveTies = granted.includes(PERMISSIONS.RANKING_RESOLVE_TIES);

  const pathways = [...new Set(view.entries.map((e) => e.pathway).filter((p): p is string => Boolean(p)))].sort();

  const filteredEntries = view.entries.filter((entry) => {
    if (params.q && !entry.applicantName.toLowerCase().includes(params.q.toLowerCase())) return false;
    if (params.pathway && entry.pathway !== params.pathway) return false;
    if (params.decisionBand && entry.decisionBand !== params.decisionBand) return false;
    if (params.tied === "true" && !entry.isTied) return false;
    return true;
  });

  const pendingTies = view.tieResolutions.filter((t) => t.status === "PENDING");
  const resolvedTies = view.tieResolutions.filter((t) => t.status === "RESOLVED");

  return (
    <div className="grid gap-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Final Ranking</h1>
          <p className="text-muted-foreground text-sm">
            {cohort.name} — Application Review (/60) + Interview (/40) = Final Score (/100)
          </p>
        </div>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">
            {view.snapshot ? (view.snapshot.isLocked ? "Ranking Approved" : "Ranking Generated") : "No ranking generated yet"}
          </CardTitle>
          <CardDescription>
            {view.snapshot
              ? `Generated by ${view.snapshot.generatedByName} on ${new Date(view.snapshot.generatedAt).toLocaleString("en-GB")} — final cohort size ${view.snapshot.targetSize}.`
              : "Generate the ranking once every eligible application has both an application review score and an interview score."}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <RankingActions
            cohortId={cohort.id}
            snapshot={view.snapshot}
            canGenerate={canGenerate}
            canApprove={canApprove}
            canReopen={canReopen}
            canExport={canExport}
            hasPendingTies={pendingTies.length > 0}
          />
        </CardContent>
      </Card>

      {pendingTies.length > 0 && (
        <div className="grid gap-3">
          <h2 className="text-lg font-semibold tracking-tight">Tie Resolution Required ({pendingTies.length})</h2>
          {pendingTies.map((tie) => (
            <TieResolutionCard key={tie.id} tie={tie} canResolve={canResolveTies} />
          ))}
        </div>
      )}

      {view.entries.length === 0 ? (
        <Card>
          <CardHeader>
            <CardTitle>Nothing ranked yet</CardTitle>
            <CardDescription>
              {view.excluded.length > 0
                ? "Every application in this cohort is still awaiting a required score — see below."
                : "No applications exist in this cohort yet."}
            </CardDescription>
          </CardHeader>
        </Card>
      ) : (
        <>
          <RankingFilterBar pathways={pathways} />

          <div className="rounded-lg border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Rank</TableHead>
                  <TableHead>Applicant</TableHead>
                  <TableHead>Pathway</TableHead>
                  <TableHead>Review (/60)</TableHead>
                  <TableHead>Interview (/40)</TableHead>
                  <TableHead>Final Score (/100)</TableHead>
                  <TableHead>Decision Band</TableHead>
                  <TableHead>Cohort</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredEntries.map((entry) => (
                  <TableRow key={entry.applicationId}>
                    <TableCell className="font-medium">{entry.rank}</TableCell>
                    <TableCell>
                      <Link href={`/ranking/${entry.applicationId}`} className="hover:underline">
                        {entry.applicantName}
                      </Link>
                      {entry.isTied && (
                        <Badge variant="outline" className="ml-2">
                          Tied
                        </Badge>
                      )}
                    </TableCell>
                    <TableCell>{entry.pathway ?? "—"}</TableCell>
                    <TableCell>{entry.reviewAverage ?? "—"}</TableCell>
                    <TableCell>{entry.interviewAverage ?? "—"}</TableCell>
                    <TableCell>
                      {entry.finalScore}
                      {entry.scoreDrifted && (
                        <Badge variant="destructive" className="ml-2">
                          Needs recalculation
                        </Badge>
                      )}
                    </TableCell>
                    <TableCell>
                      <Badge variant={DECISION_BAND_BADGE_VARIANT[entry.decisionBand]}>
                        {DECISION_BAND_LABELS[entry.decisionBand]}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      <Badge variant={entry.withinFinalCohort ? "default" : "outline"}>
                        {entry.withinFinalCohort ? "Within final cohort" : "Reserve range"}
                      </Badge>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </>
      )}

      {view.excluded.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Not yet eligible for ranking ({view.excluded.length})</CardTitle>
            <CardDescription>Excluded applications are never deleted — this is why each one is currently held out.</CardDescription>
          </CardHeader>
          <CardContent>
            <ul className="grid gap-2 text-sm">
              {view.excluded.map((item) => (
                <li key={item.applicationId} className="flex items-center justify-between gap-2 border-b pb-2 last:border-0 last:pb-0">
                  <Link href={`/applicants/${item.applicationId}`} className="hover:underline">
                    {item.applicantName}
                  </Link>
                  <Badge variant="outline">{INELIGIBILITY_LABELS[item.reason]}</Badge>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}

      {resolvedTies.length > 0 && (
        <div className="grid gap-3">
          <h2 className="text-lg font-semibold tracking-tight">Resolved Ties</h2>
          {resolvedTies.map((tie) => (
            <TieResolutionCard key={tie.id} tie={tie} canResolve={canResolveTies} />
          ))}
        </div>
      )}
    </div>
  );
}
